description = "Stage changes (git add)"

prompt = """
I will help you stage your changes.

{{#if args}}
I will execute:
!{git add {{args}}}
{{else}}
To stage all changes, I will execute:
!{git add .}
{{/if}}
"""
